export let products = [
    {
        name: "Dog food",
        image: "https://media.istockphoto.com/id/1409841711/de/foto/nassfutter-katze-isoliert-auf-wei%C3%9Fem-hintergrund.jpg?s=612x612&w=is&k=20&c=RZBHhQ4BOEuyUhMtRsGXdR62r20LUPTnGnUgrwMJcb0=",
        description:"Nutritious and delicious dog food made from high-quality ingredients to keep your furry friend healthy and happy. Available in various flavors and sizes to suit all breeds, even you, you weirdo!",
        price: 7.99,
        qtty: 1,
        available: true,
    },
    {
        name: "Cat food",
        image: "https://media.istockphoto.com/id/1318263136/de/foto/nasses-tierfutter-katze-konserven-fisch-in-einer-aluminiumdose-auf-wei%C3%9Fem-hintergrund.jpg?s=612x612&w=is&k=20&c=XKyP5wkTmej-pIK9eaOKOjp2siyDhTej_GtgGPwuHvE=",
        description:"Premium cat food designed to provide balanced nutrition for cats of all ages. Made with real meat and essential vitamins to support your cat's overall well-being. Your cat might judge you if they eat it every day though!",
        price: 3.99,
        qtty: 1,
        available: true,
    },
    {
        name: "Chewie toy",
        image: "https://cdn.pixabay.com/photo/2017/10/30/08/12/dog-2901704_640.jpg",
        description:"Durable and fun chewie toy for dogs, perfect for keeping them entertained and promoting healthy chewing habits. Made from safe, non-toxic materials. Better than having them chewing on your shoes",
        price: 12.99,
        qtty: 1,
        available: true,
    },
    {
        name: "Catnip for cats",
        image: "https://media.istockphoto.com/id/1356704429/de/foto/katze-isst-katzenminze-drau%C3%9Fen.jpg?s=612x612&w=is&k=20&c=OeAgdgGQedp7RCNV8cibHq2CTwakJCkGM7qSF4WakUw=",
        description:"High-quality catnip so you and your little buddy can be high together. Perfect for sprinkling on toys, scratching posts, or any play area to stimulate and engage your feline friend.",
        price: 4.99,
        qtty: 1,
        available: true,
    },
    {
        name: "Dog leash",
        image: "https://cdn.pixabay.com/photo/2020/11/22/20/12/rottweiler-5767824_1280.jpg",
        description:"Sturdy and comfortable dog leash, ideal for everyday walks and outdoor adventures. Features a secure clasp and an ergonomic handle for easy control. If you are in Berlin, please use on dogs only",
        price: 8.99,
        qtty: 1,
        available: false,
    },
    {
        name: "Cat scratch tree",
        image: "https://cdn.pixabay.com/photo/2017/09/26/16/11/british-shorthair-2789138_1280.jpg",
        description:"Durable cat scratch pole designed to satisfy your cat's natural scratching instincts without having to cry over the couch. Made with sisal rope and a stable base for safe play.",
        price: 14.99,
        qtty: 1,
        available: true,
    },
]